---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs","npm","unzip"]
    state: present
    update_cache: yes

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Make backend directory
  become: true
  command: mkdir -p /home/ubuntu/backend

- name: Extract archive
  unarchive:
    src: /tmp/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
